import React, { useState, useCallback } from 'react';
import { View, Text, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import RNPrint from 'react-native-print';
import Share from 'react-native-share';
import RNFS from 'react-native-fs';
import AppBar from '../../../../shared/components/AppBar';
import MainButton from '../../../../shared/components/MainButton';
import useTheme from '../../../../shared/theme/useTheme';
import GetInventoryScreenStyles from './InventoryScreenStyles';
import { getDatabase } from '../../../../shared/db/database';
import {
  getInventorySummary,
  InventorySummary,
} from '../../services/dashboardService';
import { STORE_NAME } from '../../../../configs/Constants';
import { formatDate, getTodayDateString } from '../../../../shared/utils/format';

const InventoryScreen = () => {
  const { colors } = useTheme();
  const styles = GetInventoryScreenStyles(colors);
  const [summary, setSummary] = useState<InventorySummary>({
    totalProducts: 0,
    totalStockQty: 0,
    totalSoldQty: 0,
    items: [],
  });

  useFocusEffect(
    useCallback(() => {
      const load = async () => {
        try {
          const db = await getDatabase();
          const data = await getInventorySummary(db);
          setSummary(data);
        } catch (error) {
          console.error('Failed to load inventory:', error);
        }
      };
      load();
    }, []),
  );

  const buildHtml = () => {
    const rows = summary.items
      .map(
        (item) => `
        <tr>
          <td style="padding:8px; border-bottom:1px solid #eee;">${item.name}</td>
          <td style="padding:8px; text-align:center; border-bottom:1px solid #eee; ${item.stock <= 0 ? 'color:red; font-weight:bold;' : item.stock <= 5 ? 'color:orange; font-weight:bold;' : ''}">${item.stock <= 0 ? 'OUT' : item.stock}</td>
          <td style="padding:8px; text-align:center; border-bottom:1px solid #eee;">${item.total_sold}</td>
        </tr>`,
      )
      .join('');

    return `
      <html>
      <body style="font-family:sans-serif; max-width:500px; margin:0 auto; padding:20px;">
        <h2 style="text-align:center; margin-bottom:2px;">${STORE_NAME}</h2>
        <h3 style="text-align:center; color:#666; margin-top:4px;">Inventory Summary</h3>
        <p style="text-align:center; color:#999;">${formatDate(getTodayDateString())}</p>
        <hr/>
        <div style="display:flex; justify-content:space-around; margin:16px 0;">
          <div style="text-align:center;">
            <div style="font-size:22px; font-weight:bold;">${summary.totalProducts}</div>
            <div style="color:#666; font-size:12px;">Products</div>
          </div>
          <div style="text-align:center;">
            <div style="font-size:22px; font-weight:bold; color:#00C9A7;">${summary.totalStockQty}</div>
            <div style="color:#666; font-size:12px;">In Stock</div>
          </div>
          <div style="text-align:center;">
            <div style="font-size:22px; font-weight:bold; color:#FFC107;">${summary.totalSoldQty}</div>
            <div style="color:#666; font-size:12px;">Total Sold</div>
          </div>
        </div>
        <hr/>
        <h4>Product-wise Stock</h4>
        <table style="width:100%; border-collapse:collapse;">
          <tr style="background:#6C63FF; color:white;">
            <th style="padding:8px; text-align:left;">Product</th>
            <th style="padding:8px; text-align:center;">Stock</th>
            <th style="padding:8px; text-align:center;">Sold</th>
          </tr>
          ${rows || '<tr><td colspan="3" style="padding:16px; text-align:center; color:#999;">No products</td></tr>'}
        </table>
        <hr/>
        <p style="text-align:center; color:#999; font-size:12px; margin-top:16px;">Generated by ${STORE_NAME} POS</p>
      </body>
      </html>
    `;
  };

  const handlePrint = async () => {
    await RNPrint.print({ html: buildHtml() });
  };

  const handleShare = async () => {
    try {
      const html = buildHtml();
      const path = `${RNFS.CachesDirectoryPath}/inventory-summary.html`;
      await RNFS.writeFile(path, html, 'utf8');
      await Share.open({
        url: `file://${path}`,
        type: 'text/html',
        title: 'Inventory Summary',
      });
    } catch (error: any) {
      if (error?.message !== 'User did not share') {
        console.error('Share error:', error);
      }
    }
  };

  return (
    <SafeAreaView style={styles.container} edges={['bottom']}>
      <AppBar title="Inventory Summary" />
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.summaryRow}>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryValue}>{summary.totalProducts}</Text>
            <Text style={styles.summaryLabel}>Products</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={[styles.summaryValue, styles.summaryValueGreen]}>
              {summary.totalStockQty}
            </Text>
            <Text style={styles.summaryLabel}>In Stock</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={[styles.summaryValue, styles.summaryValueOrange]}>
              {summary.totalSoldQty}
            </Text>
            <Text style={styles.summaryLabel}>Total Sold</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Product-wise Stock</Text>

        {summary.items.length > 0 ? (
          <View style={styles.tableContainer}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableHeaderText, styles.colName]}>
                Product
              </Text>
              <Text style={[styles.tableHeaderText, styles.colStock]}>
                Stock
              </Text>
              <Text style={[styles.tableHeaderText, styles.colSold]}>
                Sold
              </Text>
            </View>
            {summary.items.map((item, index) => (
              <View
                key={item.id}
                style={[
                  styles.tableRow,
                  index % 2 === 1 && styles.tableRowAlt,
                ]}>
                <Text
                  style={[styles.cellBold, styles.colName]}
                  numberOfLines={1}>
                  {item.name}
                </Text>
                <Text
                  style={[
                    styles.cellText,
                    styles.colStock,
                    item.stock <= 5 && item.stock > 0 && styles.stockLow,
                    item.stock <= 0 && styles.stockOut,
                  ]}>
                  {item.stock <= 0 ? 'OUT' : item.stock}
                </Text>
                <Text style={[styles.cellText, styles.colSold]}>
                  {item.total_sold}
                </Text>
              </View>
            ))}
          </View>
        ) : (
          <Text style={styles.emptyText}>No products added yet</Text>
        )}

        <View style={styles.actionRow}>
          <View style={styles.actionButton}>
            <MainButton title="Print" onPress={handlePrint} />
          </View>
          <View style={styles.actionButton}>
            <MainButton title="Share" onPress={handleShare} outline />
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

export default InventoryScreen;
