import React, { useState, useCallback, useMemo } from 'react';
import { View, Text, ScrollView } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import RNPrint from 'react-native-print';
import Share from 'react-native-share';
import RNFS from 'react-native-fs';
import AppBar from '../../../../shared/components/AppBar';
import SupplierFilterDropdown from '../../../../shared/components/SupplierFilterDropdown';
import useTheme from '../../../../shared/theme/useTheme';
import GetInventoryScreenStyles from './InventoryScreenStyles';
import { getDatabase } from '../../../../shared/db/database';
import {
  getInventorySummary,
  InventorySummary,
} from '../../services/dashboardService';
import { Supplier } from '../../../../shared/types';
import { getAllSuppliers } from '../../../suppliers/services/supplierService';
import { STORE_NAME } from '../../../../configs/Constants';
import { formatDate, getTodayDateString } from '../../../../shared/utils/format';

const InventoryScreen = () => {
  const { colors } = useTheme();
  const styles = GetInventoryScreenStyles(colors);
  const [summary, setSummary] = useState<InventorySummary>({
    totalProducts: 0,
    totalStockQty: 0,
    totalSoldQty: 0,
    items: [],
  });
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [filterSupplierId, setFilterSupplierId] = useState<number | null>(null);

  useFocusEffect(
    useCallback(() => {
      const load = async () => {
        try {
          const db = await getDatabase();
          const [data, suppData] = await Promise.all([
            getInventorySummary(db),
            getAllSuppliers(db),
          ]);
          setSummary(data);
          setSuppliers(suppData);
        } catch (error) {
          console.error('Failed to load inventory:', error);
        }
      };
      load();
    }, []),
  );

  const filteredItems = useMemo(() => {
    if (filterSupplierId === null) return summary.items;
    return summary.items.filter((item) => item.supplier_id === filterSupplierId);
  }, [summary.items, filterSupplierId]);

  const buildHtml = () => {
    const rows = filteredItems
      .map(
        (item) => `
        <tr>
          <td style="padding:8px; border-bottom:1px solid #eee;">${item.name}</td>
          <td style="padding:8px; text-align:center; border-bottom:1px solid #eee; ${item.stock <= 0 ? 'color:red; font-weight:bold;' : item.stock <= 5 ? 'color:orange; font-weight:bold;' : ''}">${item.stock <= 0 ? 'OUT' : item.stock}</td>
          <td style="padding:8px; text-align:center; border-bottom:1px solid #eee;">${item.total_sold}</td>
        </tr>`,
      )
      .join('');

    return `
      <html>
      <body style="font-family:sans-serif; max-width:500px; margin:0 auto; padding:20px;">
        <h2 style="text-align:center; margin-bottom:2px;">${STORE_NAME}</h2>
        <h3 style="text-align:center; color:#666; margin-top:4px;">Inventory Summary</h3>
        <p style="text-align:center; color:#999;">${formatDate(getTodayDateString())}</p>
        <hr/>
        <div style="display:flex; justify-content:space-around; margin:16px 0;">
          <div style="text-align:center;">
            <div style="font-size:22px; font-weight:bold;">${summary.totalProducts}</div>
            <div style="color:#666; font-size:12px;">Products</div>
          </div>
          <div style="text-align:center;">
            <div style="font-size:22px; font-weight:bold; color:#00C9A7;">${summary.totalStockQty}</div>
            <div style="color:#666; font-size:12px;">In Stock</div>
          </div>
          <div style="text-align:center;">
            <div style="font-size:22px; font-weight:bold; color:#FFC107;">${summary.totalSoldQty}</div>
            <div style="color:#666; font-size:12px;">Total Sold</div>
          </div>
        </div>
        <hr/>
        <h4>Product-wise Stock</h4>
        <table style="width:100%; border-collapse:collapse;">
          <tr style="background:#6C63FF; color:white;">
            <th style="padding:8px; text-align:left;">Product</th>
            <th style="padding:8px; text-align:center;">Stock</th>
            <th style="padding:8px; text-align:center;">Sold</th>
          </tr>
          ${rows || '<tr><td colspan="3" style="padding:16px; text-align:center; color:#999;">No products</td></tr>'}
        </table>
        <hr/>
        <p style="text-align:center; color:#999; font-size:12px; margin-top:16px;">Generated by ${STORE_NAME} POS</p>
      </body>
      </html>
    `;
  };

  const handlePrint = async () => {
    await RNPrint.print({ html: buildHtml() });
  };

  const handleShare = async () => {
    try {
      const html = buildHtml();
      const path = `${RNFS.CachesDirectoryPath}/inventory-summary.html`;
      await RNFS.writeFile(path, html, 'utf8');
      await Share.open({
        url: `file://${path}`,
        type: 'text/html',
        title: 'Inventory Summary',
      });
    } catch (error: any) {
      if (error?.message !== 'User did not share') {
        console.error('Share error:', error);
      }
    }
  };

  return (
    <SafeAreaView style={styles.container} edges={['bottom']}>
      <AppBar
        title="Inventory Summary"
        rightActions={[
          {
            icon: (
              <Svg width={22} height={22} viewBox="0 0 24 24" fill="none">
                <Path
                  d="M19 8h-1V3H6v5H5c-1.66 0-3 1.34-3 3v6h4v4h12v-4h4v-6c0-1.66-1.34-3-3-3zM8 5h8v3H8V5zm8 14H8v-4h8v4zm2-4v-2H6v2H4v-4c0-.55.45-1 1-1h14c.55 0 1 .45 1 1v4h-2z"
                  fill="#FFFFFF"
                />
              </Svg>
            ),
            onPress: handlePrint,
          },
          {
            icon: (
              <Svg width={22} height={22} viewBox="0 0 24 24" fill="none">
                <Path
                  d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92s2.92-1.31 2.92-2.92-1.31-2.92-2.92-2.92z"
                  fill="#FFFFFF"
                />
              </Svg>
            ),
            onPress: handleShare,
          },
        ]}
      />
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.summaryRow}>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryValue}>{summary.totalProducts}</Text>
            <Text style={styles.summaryLabel}>Products</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={[styles.summaryValue, styles.summaryValueGreen]}>
              {summary.totalStockQty}
            </Text>
            <Text style={styles.summaryLabel}>In Stock</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={[styles.summaryValue, styles.summaryValueOrange]}>
              {summary.totalSoldQty}
            </Text>
            <Text style={styles.summaryLabel}>Total Sold</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Product-wise Stock</Text>

        <SupplierFilterDropdown
          suppliers={suppliers}
          selectedId={filterSupplierId}
          onSelect={setFilterSupplierId}
        />

        {filteredItems.length > 0 ? (
          <View style={styles.tableContainer}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableHeaderText, styles.colName]}>
                Product
              </Text>
              <Text style={[styles.tableHeaderText, styles.colStock]}>
                Stock
              </Text>
              <Text style={[styles.tableHeaderText, styles.colSold]}>
                Sold
              </Text>
            </View>
            {filteredItems.map((item, index) => (
              <View
                key={item.id}
                style={[
                  styles.tableRow,
                  index % 2 === 1 && styles.tableRowAlt,
                ]}>
                <Text
                  style={[styles.cellBold, styles.colName]}
                  numberOfLines={1}>
                  {item.name}
                </Text>
                <Text
                  style={[
                    styles.cellText,
                    styles.colStock,
                    item.stock <= 5 && item.stock > 0 && styles.stockLow,
                    item.stock <= 0 && styles.stockOut,
                  ]}>
                  {item.stock <= 0 ? 'OUT' : item.stock}
                </Text>
                <Text style={[styles.cellText, styles.colSold]}>
                  {item.total_sold}
                </Text>
              </View>
            ))}
          </View>
        ) : (
          <Text style={styles.emptyText}>No products added yet</Text>
        )}

      </ScrollView>
    </SafeAreaView>
  );
};

export default InventoryScreen;
