import React, { useCallback } from 'react';
import { View, Text, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import RNPrint from 'react-native-print';
import Share from 'react-native-share';
import RNFS from 'react-native-fs';
import AppBar from '../../../../shared/components/AppBar';
import MainButton from '../../../../shared/components/MainButton';
import useTheme from '../../../../shared/theme/useTheme';
import GetDailyReportScreenStyles from './DailyReportScreenStyles';
import useDailyReport from '../../hooks/useDailyReport';
import { formatCurrency, formatDate, getTodayDateString } from '../../../../shared/utils/format';
import { STORE_NAME } from '../../../../configs/Constants';

const DailyReportScreen = () => {
  const { colors } = useTheme();
  const styles = GetDailyReportScreenStyles(colors);
  const { date, summary, isLoading, loadReport } = useDailyReport();

  useFocusEffect(
    useCallback(() => {
      loadReport(getTodayDateString());
    }, []),
  );

  const isToday = date === getTodayDateString();

  const buildReportHtml = () => {
    const rows = summary.items
      .map(
        (item) => `
        <tr>
          <td style="padding:8px; border-bottom:1px solid #eee;">${item.product_name}</td>
          <td style="padding:8px; text-align:center; border-bottom:1px solid #eee;">${item.total_quantity}</td>
          <td style="padding:8px; text-align:right; border-bottom:1px solid #eee;">${formatCurrency(item.total_revenue)}</td>
        </tr>`,
      )
      .join('');

    return `
      <html>
      <body style="font-family:sans-serif; max-width:500px; margin:0 auto; padding:20px;">
        <h2 style="text-align:center; margin-bottom:2px;">${STORE_NAME}</h2>
        <h3 style="text-align:center; color:#666; margin-top:4px;">Daily Sales Report</h3>
        <p style="text-align:center; color:#999;">${formatDate(date)}${isToday ? ' (Today)' : ''}</p>
        <hr/>
        <div style="display:flex; justify-content:space-around; margin:16px 0;">
          <div style="text-align:center;">
            <div style="font-size:24px; font-weight:bold;">${formatCurrency(summary.totalSales)}</div>
            <div style="color:#666; font-size:12px;">Total Revenue</div>
          </div>
          <div style="text-align:center;">
            <div style="font-size:24px; font-weight:bold;">${summary.totalTransactions}</div>
            <div style="color:#666; font-size:12px;">Transactions</div>
          </div>
        </div>
        <hr/>
        <h4>Item-wise Breakdown</h4>
        <table style="width:100%; border-collapse:collapse;">
          <tr style="background:#6C63FF; color:white;">
            <th style="padding:8px; text-align:left;">Product</th>
            <th style="padding:8px; text-align:center;">Qty</th>
            <th style="padding:8px; text-align:right;">Revenue</th>
          </tr>
          ${rows || '<tr><td colspan="3" style="padding:16px; text-align:center; color:#999;">No sales</td></tr>'}
        </table>
        <hr/>
        <p style="text-align:center; color:#999; font-size:12px; margin-top:16px;">Generated by ${STORE_NAME} POS</p>
      </body>
      </html>
    `;
  };

  const handlePrint = async () => {
    await RNPrint.print({ html: buildReportHtml() });
  };

  const handleShare = async () => {
    try {
      const html = buildReportHtml();
      const path = `${RNFS.CachesDirectoryPath}/daily-report-${date}.html`;
      await RNFS.writeFile(path, html, 'utf8');
      await Share.open({
        url: `file://${path}`,
        type: 'text/html',
        title: `Daily Report - ${formatDate(date)}`,
      });
    } catch (error: any) {
      if (error?.message !== 'User did not share') {
        console.error('Share error:', error);
      }
    }
  };

  return (
    <SafeAreaView style={styles.container} edges={['bottom']}>
      <AppBar title="Daily Report" />
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.dateContainer}>
          <Text style={styles.dateText}>
            {formatDate(date)}
          </Text>
          {isToday && <Text style={styles.dateLabel}>Today</Text>}
        </View>

        <View style={styles.summaryRow}>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryValue}>
              {formatCurrency(summary.totalSales)}
            </Text>
            <Text style={styles.summaryLabel}>Total Revenue</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryValue}>
              {summary.totalTransactions}
            </Text>
            <Text style={styles.summaryLabel}>Transactions</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Item-wise Breakdown</Text>

        {summary.items.length > 0 ? (
          <View style={styles.tableContainer}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableHeaderText, styles.colProduct]}>
                Product
              </Text>
              <Text style={[styles.tableHeaderText, styles.colQty]}>
                Qty
              </Text>
              <Text style={[styles.tableHeaderText, styles.colRevenue]}>
                Revenue
              </Text>
            </View>
            {summary.items.map((item, index) => (
              <View
                key={index}
                style={[
                  styles.tableRow,
                  index % 2 === 1 && styles.tableRowAlt,
                ]}>
                <Text
                  style={[styles.tableCellBold, styles.colProduct]}
                  numberOfLines={1}>
                  {item.product_name}
                </Text>
                <Text style={[styles.tableCell, styles.colQty]}>
                  {item.total_quantity}
                </Text>
                <Text style={[styles.tableCell, styles.colRevenue]}>
                  {formatCurrency(item.total_revenue)}
                </Text>
              </View>
            ))}
          </View>
        ) : (
          <Text style={styles.emptyReport}>
            {isLoading ? 'Loading...' : 'No sales recorded for this day'}
          </Text>
        )}

        <View style={styles.actionRow}>
          <View style={styles.actionButton}>
            <MainButton title="Print" onPress={handlePrint} />
          </View>
          <View style={styles.actionButton}>
            <MainButton title="Share" onPress={handleShare} outline />
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

export default DailyReportScreen;
